"""Renamed Token Field

Revision ID: 573c89266a1f
Revises: f5adac979bea
Create Date: 2019-08-30 17:45:45.565527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573c89266a1f'
down_revision = 'f5adac979bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('reset_token', sa.Text(), nullable=False))
    op.drop_column('password_resets', 'activation_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('activation_token', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('password_resets', 'reset_token')
    # ### end Alembic commands ###
